[project]
name = "studios-launch-page"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=2.0.0",
    "gunicorn>=20.1.0",
    "requests>=2.28.0",
    "types-requests>=2.28.0",
]
